### ISSUE TITLE
Minor improvements to get done this week

### ISSUE THREAD

**Issue by EarlJr53** [LongMetal-Robotics/Infinite-Recharge#70]
We have quite a few small things to get done and perfect this week.
- [ ] Add more auto modes #53 
    - I will work on this, but @jon-pun and @fjfur10 can also work on it some.
- [ ] Test current auto modes (including on taped-out field layout) #53 
    - [ ] Work with carpentry people (?) to put down accurate tape layout of half the field somewhere in the school where (hopefully) we won't have to take it up everyday.
- [ ] Try writing auto modes with PathWeaver #53 
    - @jon-pun and @fjfur10 I would like you two to continue to work on this if possible, as you have the most experience with PathWeaver at this point. Create your paths assuming we will have an IMU. Also, if you can start adding the code to import the Paths, that would be wonderful. Please do that in <Auto>.
- [ ] Add manual controls for everything and rework some controls #64 
    - Given that I wrote all the other controls, I will likely continue to work on them, and keep in touch with our drive team about what they want.
- [ ] Move Limelight to other crossbar
    - Mechanical needs to make the crossbar a bit more solid, but if @achkvina or @Sky14r are at a meeting this week and need something to do, this needs to get done. We may have to also change the current crossbar over the shooter if it's gonna get in the line of sight of the new Limelight placement.
- [ ] Fix control panel code and test it
    - We haven't gotten a chance to test the code that @jon-pun and @fjfur10 wrote. I would like to talk to them about how to properly implement it (it hasn't been called by Robot.java yet), and then try to test it and figure out what needs to be fixed.
- [ ] More PID tuning #69 
    - This isn't urgent at this point, but it's something that only needs @i-am-gizm0 to do.
- [ ] Tune shooter conversion factor and test from multiple angles relative to target (related to #69 )
    - This will help our consistency and help the balls not bounce back out.
- [ ] Mount LED strips inside drivetrain so that we have that out of the way while we have our hands on the robot now. Once other people take the robot back, I want to be able to have them in place so that we just have to worry about their code. #57 
    - I will probably do this, with help from @achkvina 
- [ ] Order Pigeon IMU (I feel like we had one, but I may be delusional; either way we need one). We just have to send it along to one of the mentors to order.
    - I will probably send this along to Lee and PDunks soon.
- [ ] Have the control panel go up and down fairly quickly at the beginning of auto to release the intake
    - I can do this, or @AndreasDuma or @jon-pun probably
- [ ] Tune low port mode
    - I will do this hopefully soon, but it's not urgent.

I know this was a lot, but it's pretty much all the stuff I can think of at the moment that we need to do for now. Some of this stuff will be assignable to those who have done less code, some of it pretty much needs to be done by myself and Sam.
